name = "gpt-shutdown-worker"
main = "src/shutdown.js"
compatibility_date = "2025-08-06"

[vars]
RUNPOD_API_KEY = "your_runpod_api_key"
RUNPOD_POD_ID = "your_pod_id"
INACTIVITY_LIMIT_MINUTES = "10"

[[kv_namespaces]]
binding = "LAST_REQUEST_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[triggers]
crons = ["*/5 * * * *"] # runs every 5 minutes
